name: docs

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build:
    name: 🛠️ Build Documentation Site
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 📦 Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🏗️ Build Site with MkDocs
        run: mkdocs build

  deploy:
    name: 🚀 Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🌐 Deploy Site to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          clean-exclude: pr-preview/

  pr-preview:
    name: 🔍 Create PR Preview
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action != 'closed'

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🛠️ Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site
          preview-branch: gh-pages
          umbrella-dir: pr-preview

  remove-pr-preview:
    name: 🗑️ Remove PR Preview
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'

    steps:
      - name: ⬇️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🗑️ Remove PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: site
          action: remove
